### ISSUE TITLE
Error getting Arkose token:  captcha required

### ISSUE THREAD

**Issue by bi1101** [xqdoo00o/ChatGPT-to-API#15]
自今天开始就出现了这个错误，我试过代理、高级账号、HAR、Cookie，但似乎无法绕过它。你知道发生了什么事吗？

**Comment by xqdoo00o** [comment]
你的ip可能是提问太多，被标记了，需要手动captcha，可以换个ip试试

**Comment by bi1101** [comment]
问题解决了！非常感谢

**Comment by bi1101** [comment]
似乎问题再次发生，我在该IP上解决了验证码并记录了HAR文件，但在API的几次请求之后，又需要验证码。

然而，当我停止了API的请求，只在ChatGPT网站上进行请求时，没有要求验证码。

看来OpenAI可以区分两种请求，并只阻止API的请求。

目前，使用代理暂时解决了这个问题，但OpenAI可能会在未来加强限制。

**Comment by xqdoo00o** [comment]
> 似乎问题再次发生，我在该IP上解决了验证码并记录了HAR文件，但在API的几次请求之后，又需要验证码。
> 
> 然而，当我停止了API的请求，只在ChatGPT网站上进行请求时，没有要求验证码。
> 
> 看来OpenAI可以区分两种请求，并只阻止API的请求。
> 
> 目前，使用代理暂时解决了这个问题，但OpenAI可能会在未来加强限制。

是的，确定是ip的问题，即使手动captcha通过后，也只能维持几分钟有效。如果你的使用量真的很大的话，建议上ip代理池和har池，轮询使用。

**Comment by bi1101** [comment]
谢，你能告诉我如何调整代码来使用HAR池吗？

**Comment by xqdoo00o** [comment]
> 谢，你能告诉我如何调整代码来使用HAR池吗？

目前不支持，是在[funcatcha](https://github.com/xqdoo00o/funcaptcha)仓库里读取的har，你可以把api.go里chatArk的类型改为[]*arkReq，并循环读取har文件并赋值给chatArk，sendRequest函数里轮询读取chatArk

**Comment by xqdoo00o** [comment]
> > 谢，你能告诉我如何调整代码来使用HAR池吗？
> 
> 目前不支持，是在[funcatcha](https://github.com/xqdoo00o/funcaptcha)仓库里读取的har，你可以把api.go里chatArk的类型改为[]*arkReq，并循环读取har文件池并赋值给chatArk，sendRequest函数里轮询使用chatArk发送请求

最新版本支持har池了，请把所有har文件放到harPool文件夹里，使用最新版本即可
