### ISSUE TITLE
最新版有错误，无法运行

### ISSUE THREAD

**Issue by Plus-xu** [xqdoo00o/ChatGPT-to-API#17]
运行环境：docker
最新版更改了har的位置，我修改docker compose设置，把har文件挂载到容器:/app/harPool/chat.openai.com.har但是却无法正常运行，访问api全都返回无响应，尝试修改har到根目录，访问api依然无响应
{
  "error": true,
  "message": "empty response"
}

切换回[92d55a9](https://github.com/xqdoo00o/ChatGPT-to-API/commit/92d55a92ecddc6add54d2773c6ac7a0c643d12f0)后可以正常运行
查看了下修改日志，似乎没有修改har的访问位置？之前直接放到根目录是可以正常识别的

**Comment by Plus-xu** [comment]
还有一个问题，利用plus转的api在chatgpt sidebar等应用使用的时候，会弹出错误，只能选择chatgpt 3.5，识别不出4.0，有人知道这个怎么解决吗？感谢！
https://pic7.58cdn.com.cn/nowater/webim/big/n_v26181730b1ae7452f81451506551fc049.png

**Comment by xqdoo00o** [comment]
{
"error": true,
"message": "empty response"
}
是哪一行报的错误

**Comment by xqdoo00o** [comment]
尝试修复了，用最新版再尝试下，
另外最新版区分了3.5和4的har请求，也就是你请求3.5，要用包含gpt-3.5请求的har文件。可以参考下readme，重新导出下3.5和4的har文件

**Comment by xqdoo00o** [comment]
> 还有一个问题请教，利用plus转的api在chatgpt sidebar等应用使用的时候，会弹出错误，只能选择chatgpt 3.5，识别不出4.0，有人知道这个怎么解决吗？感谢！ ![20231102114735096](https://user-images.githubusercontent.com/52371609/279862683-c21609ad-75fa-4d26-bc99-5fa5cc1bc3e5.png)

这个是因为少了个v1/models接口，最新版已经添加了，可以试下

**Comment by Plus-xu** [comment]
> 尝试修复了，用最新版再尝试下。 你是gpt-3.5和4都不能用吗？ 估计是因为最新版区分了3.5和4的har请求，也就是你请求3.5，要用包含gpt-3.5请求的har文件。可以参考下readme，重新导出下3.5和4的har文件。

```
chatgpttoapi  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
chatgpttoapi  |  - using env:	export GIN_MODE=release
chatgpttoapi  |  - using code:	gin.SetMode(gin.ReleaseMode)
chatgpttoapi  | 
chatgpttoapi  | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
chatgpttoapi  | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
chatgpttoapi  | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
chatgpttoapi  | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
chatgpttoapi  | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
chatgpttoapi  | 2023/11/02 03:01:20 1 0.0.0.0:8080
chatgpttoapi  | [GIN] 2023/11/02 - 03:01:27 | 500 |    1.160757ms |    2.2.2.2 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
chatgpttoapi  | 
chatgpttoapi  | 
chatgpttoapi  | 2023/11/02 03:01:27 [Recovery] 2023/11/02 - 03:01:27 panic recovered:
```


我前几天是通过使用4.0问问题导出的har，在chatgpt-web-next等工具用api接口问答时，可以正常使用4,0和3.0，但是有的工具不能选择4.0只能选4.0-32k等其它选项时，有时会出现一直在等待无法相应，或者只能显示回答中的一句话，这时候去chatgpt官网可以看到chatgpt已经回复了，刷新网页，应用端有时就能继续补充完整回复，不知道是这些应用的问题还是接口的问题。我晚些时候会试下刚才的新版本，有问题再上报。

**Comment by xqdoo00o** [comment]
> > 尝试修复了，用最新版再尝试下。 你是gpt-3.5和4都不能用吗？ 估计是因为最新版区分了3.5和4的har请求，也就是你请求3.5，要用包含gpt-3.5请求的har文件。可以参考下readme，重新导出下3.5和4的har文件。
> 
> ```
>  ✔ Container chatgpttoapi  Created                                                                                                      0.0s 
> Attaching to chatgpttoapi
> chatgpttoapi  | Error: please put HAR files in harPool directory!
> chatgpttoapi  | Updating access token for shifeihome@gmail.com
> chatgpttoapi  | Success!
> chatgpttoapi  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
> chatgpttoapi  | 
> 
> chatgpttoapi  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
> chatgpttoapi  |  - using env:	export GIN_MODE=release
> chatgpttoapi  |  - using code:	gin.SetMode(gin.ReleaseMode)
> chatgpttoapi  | 
> chatgpttoapi  | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
> chatgpttoapi  | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
> chatgpttoapi  | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
> chatgpttoapi  | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
> chatgpttoapi  | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
> chatgpttoapi  | 2023/11/02 03:01:20 1 0.0.0.0:8080
> chatgpttoapi  | [GIN] 2023/11/02 - 03:01:27 | 500 |    1.160757ms |    2.2.2.2 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
> chatgpttoapi  | 
> chatgpttoapi  | 
> chatgpttoapi  | 2023/11/02 03:01:27 [Recovery] 2023/11/02 - 03:01:27 panic recovered:
> ```
> 
> 我前几天是通过使用4.0问问题导出的har，在chatgpt-web-next等工具用api接口问答时，可以正常使用4,0和3.0，但是有的工具不能选择4.0只能选4.0-32k等其它选项时，有时会出现一直在等待无法相应，或者只能显示回答中的一句话，这时候去chatgpt官网可以看到chatgpt已经回复了，刷新网页，应用端有时就能继续补充完整回复，不知道是这些应用的问题还是接口的问题。我晚些时候会试下刚才的新版本，有问题再上报。

嗯，之前的版本是可以问3.5问题用4的har文件的，都可以互相混用，但是我的har这样用了几天3.5会不出码了。
所以当前版本就区分开了。

**Comment by Plus-xu** [comment]
> > > 尝试修复了，用最新版再尝试下。 你是gpt-3.5和4都不能用吗？ 估计是因为最新版区分了3.5和4的har请求，也就是你请求3.5，要用包含gpt-3.5请求的har文件。可以参考下readme，重新导出下3.5和4的har文件。
> > 
> > 
> > ```
> >  ✔ Container chatgpttoapi  Created                                                                                                      0.0s 
> > Attaching to chatgpttoapi
> > chatgpttoapi  | Error: please put HAR files in harPool directory!
> > chatgpttoapi  | Updating access token for shifeihome@gmail.com
> > chatgpttoapi  | Success!
> > chatgpttoapi  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
> > chatgpttoapi  | 
> > 
> > chatgpttoapi  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
> > chatgpttoapi  |  - using env:	export GIN_MODE=release
> > chatgpttoapi  |  - using code:	gin.SetMode(gin.ReleaseMode)
> > chatgpttoapi  | 
> > chatgpttoapi  | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
> > chatgpttoapi  | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
> > chatgpttoapi  | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
> > chatgpttoapi  | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
> > chatgpttoapi  | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
> > chatgpttoapi  | 2023/11/02 03:01:20 1 0.0.0.0:8080
> > chatgpttoapi  | [GIN] 2023/11/02 - 03:01:27 | 500 |    1.160757ms |    2.2.2.2 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
> > chatgpttoapi  | 
> > chatgpttoapi  | 
> > chatgpttoapi  | 2023/11/02 03:01:27 [Recovery] 2023/11/02 - 03:01:27 panic recovered:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我前几天是通过使用4.0问问题导出的har，在chatgpt-web-next等工具用api接口问答时，可以正常使用4,0和3.0，但是有的工具不能选择4.0只能选4.0-32k等其它选项时，有时会出现一直在等待无法相应，或者只能显示回答中的一句话，这时候去chatgpt官网可以看到chatgpt已经回复了，刷新网页，应用端有时就能继续补充完整回复，不知道是这些应用的问题还是接口的问题。我晚些时候会试下刚才的新版本，有问题再上报。
> 
> 嗯，之前的版本是可以问3.5问题用4的har文件的，都可以互相混用，但是我的har这样用了几天3.5会不出码了。 所以当前版本就区分开了。

我刚才贴的日志错了，重新更新了下，你看看

**Comment by xqdoo00o** [comment]
> > > > 尝试修复了，用最新版再尝试下。 你是gpt-3.5和4都不能用吗？ 估计是因为最新版区分了3.5和4的har请求，也就是你请求3.5，要用包含gpt-3.5请求的har文件。可以参考下readme，重新导出下3.5和4的har文件。
> > > 
> > > 
> > > ```
> > >  ✔ Container chatgpttoapi  Created                                                                                                      0.0s 
> > > Attaching to chatgpttoapi
> > > chatgpttoapi  | Error: please put HAR files in harPool directory!
> > > chatgpttoapi  | Updating access token for shifeihome@gmail.com
> > > chatgpttoapi  | Success!
> > > chatgpttoapi  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
> > > chatgpttoapi  | 
> > > 
> > > chatgpttoapi  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
> > > chatgpttoapi  |  - using env:	export GIN_MODE=release
> > > chatgpttoapi  |  - using code:	gin.SetMode(gin.ReleaseMode)
> > > chatgpttoapi  | 
> > > chatgpttoapi  | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
> > > chatgpttoapi  | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
> > > chatgpttoapi  | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
> > > chatgpttoapi  | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
> > > chatgpttoapi  | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
> > > chatgpttoapi  | 2023/11/02 03:01:20 1 0.0.0.0:8080
> > > chatgpttoapi  | [GIN] 2023/11/02 - 03:01:27 | 500 |    1.160757ms |    2.2.2.2 | POST     "/v1/chat/completions?path=v1&path=chat&path=completions"
> > > chatgpttoapi  | 
> > > chatgpttoapi  | 
> > > chatgpttoapi  | 2023/11/02 03:01:27 [Recovery] 2023/11/02 - 03:01:27 panic recovered:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我前几天是通过使用4.0问问题导出的har，在chatgpt-web-next等工具用api接口问答时，可以正常使用4,0和3.0，但是有的工具不能选择4.0只能选4.0-32k等其它选项时，有时会出现一直在等待无法相应，或者只能显示回答中的一句话，这时候去chatgpt官网可以看到chatgpt已经回复了，刷新网页，应用端有时就能继续补充完整回复，不知道是这些应用的问题还是接口的问题。我晚些时候会试下刚才的新版本，有问题再上报。
> > 
> > 
> > 嗯，之前的版本是可以问3.5问题用4的har文件的，都可以互相混用，但是我的har这样用了几天3.5会不出码了。 所以当前版本就区分开了。
> 
> 我刚才贴的日志错了，重新更新了下，你看看

嗯嗯，你用最新版本+包含3.5的har文件应该就能正常用3.5了

**Comment by Plus-xu** [comment]
上面2个回复引用的代码里不小心把邮箱暴露了，能删一下吗，感谢

**Comment by xqdoo00o** [comment]
已修复，请用最新版本，并使用参考文档导出的包含3.5(以及4)的har文件。

**Comment by Plus-xu** [comment]
> 已修复，请用最新版本，并使用参考文档导出的包含3.5(以及4)的har文件。

已经更新到最新版了，目前使用gpt3和gpt4都正常，这次更新以后，通过API进行的问答和回复，不会在官网上显示和记录了，非常方便。
目前回答延迟比较大，比如选择gpt4-32k-0613，AI回复400字左右大约需要30到40秒以上才能完全显示出来。
上面提到的应用无法通过API识别选择模型的问题，依然存在，通过chatgpt sidebar选择模型时，api接口显示如下信息
```
chatgpttoapi  | [GIN] 2023/11/02 - 13:50:34 | 404 |      48.685µs |    x.x.x.x | GET      "//v1/models"
chatgpttoapi  | [GIN] 2023/11/02 - 13:52:31 | 404 |      47.795µs |    x.x.x.x | GET      "//v1/models"
```
似乎是"//v1/models" 多了一个"/"导致路径错误？
感谢帮助！

**Comment by Plus-xu** [comment]
> > 已修复，请用最新版本，并使用参考文档导出的包含3.5(以及4)的har文件。
> 
> 已经更新到最新版了，gpt3和gpt4都正常，这次更新以后，通过API进行的对话，不会在官网上显示和记录了，非常方便。 目前回答延迟比较大，比如选择gpt4-32k-0613，AI回复400字左右大约需要30到40秒以上才能完全显示出来。 上面提到的应用无法通过API识别选择模型的问题，依然存在，通过chatgpt sidebar选择模型时，api接口显示如下信息
> 
> ```
> chatgpttoapi  | [GIN] 2023/11/02 - 13:50:34 | 404 |      48.685µs |    x.x.x.x | GET      "//v1/models"
> chatgpttoapi  | [GIN] 2023/11/02 - 13:52:31 | 404 |      47.795µs |    x.x.x.x | GET      "//v1/models"
> ```
> 
> 似乎是"//v1/models" 多了一个"/"导致路径错误？ 感谢帮助！

我把接口地址从https://x.x.x.x/ 修改成https://x.x.x.x 后可以正常选择模型了，感谢！
