### ISSUE TITLE
用docker运行的话，怎样挂载account.txt文件呢

### ISSUE THREAD

**Issue by zhuxindong** [xqdoo00o/ChatGPT-to-API#2]
用docker运行的话，怎样挂载account.txt文件呢，映射路径是什么

**Comment by xqdoo00o** [comment]
没用过docker，应该是跟可执行文件freechatgpt同一目录的

**Comment by xqdoo00o** [comment]
参考该[issue](https://github.com/acheong08/ChatGPT-to-API/issues/112)
