### ISSUE TITLE
如何配置多个oauth账号？

### ISSUE THREAD

**Issue by dreammis** [xqdoo00o/ChatGPT-to-API#20]
我尝试在cookie.json中增加多个账号，在accounts.txt中配置相同多个账号
貌似是不行的，请问有办法配置多账号，负载均衡吗。

另外我在使用的过程中，常常会遇到无响应的情况，但是重启容器后，就恢复正常了。不知道你是否遇到过。这个该怎么解决。

**Comment by bi1101** [comment]
This is a recent error, it seems that the requesting client is the problem and open ai has implemented some csrf when authenticating. No fixes for that yet. 
Not sure if this would help but here is another repo that has fixed this
https://github.com/gngpp/ninja/commit/40fb18e756141a20a8c14d17c57e57f2fae838e0

**Comment by bi1101** [comment]
The issue seems to have resolve itself
