### ISSUE TITLE
无法使用OpenAI Embeddings Model

### ISSUE THREAD

**Issue by Plus-xu** [xqdoo00o/ChatGPT-to-API#25]
plus转换的api似乎无法使用embeddings model（https://api.openai.com/v1/embeddings ），返回404 page not found，自建的API可以访问/v1/embeddings这个api，但是好像无法获取返回的内容？
目前在用的几个文本向量化的基于ai的知识库都无法利用openai的embedding model （text-embedding-ada-002）
使用gpt-4-vision-preview，如果询问openai是哪个模型，它会回答自己是gpt3.5，好像这个目前也没法使用

**Comment by xqdoo00o** [comment]
目前只是转换网页版chatgpt到聊天api(v1/chat/completions)，不是完全模拟api.openai.com的功能
