### ISSUE TITLE
Updating access token for vdmg××××@email.com，Error getting auth Arkose token

### ISSUE THREAD

**Issue by AireWong** [xqdoo00o/ChatGPT-to-API#26]
**Here is the configuration file in the root directory of my project**
- freechatgpt
- accounts.txt : `vdmg××××@email.com:9zok2×××`
- access_tokens.json :  `{}`
- **harPool** folder >> chat.openai.com.har
- cookies.json : 
```
{
    "Email": [
        {
            "Name": "__Secure-next-auth.session-token",
            "Value": "eyJhbGciOiJkaXIiLC......",
            "Path": "/",
            "Domain": "",
            "Expires": "0001-01-01T00:00:00Z",
            "MaxAge": 0,
            "Secure": true,
            "HttpOnly": true,
            "SameSite": 2,
            "Unparsed": null
        }
    ]
}
```

When I run the command `./freechatgpt` the following error occurs.  **Error getting auth Arkose token**

![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/129597116/291de64c-9cf4-4fe9-8dec-b09a36e85753)

I appreciate any response from anyone. Thank you.

**Comment by bi1101** [comment]
I think you didn't turn on ``preserve log & disable cache`` in Chrome Network dev tab to save the arkose to the HAR file. You must also log out from the ChatGPT account -> turn on dev settings and log the HAR-> enter a few chats for both GPT 3&4 -> save the HAR.

With this being said, I think you should consider sponsoring @xqdoo00o if you find this repo valuable

@xqdoo00o Can you set up a sponsor link sir? I would like to sponsor this repo.
