### ISSUE TITLE
接口的所有回答为空

### ISSUE THREAD

**Issue by FightingSu** [xqdoo00o/ChatGPT-to-API#28]
这两天 OpenAI 貌似修改了一些东西，所有的请求返回的信息都是空的。比如下面的例子：

```bash
user@machine ~ % curl http://127.0.0.1:8080/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H 'Authorization: Bearer Testing' \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "???"
      }
    ]
  }'
```

其中返回的内容中，`message` 字段为：

```bash
"message":{
  "role":"assistant",
  "content":""
}
```

参考其他项目的 issue，发现可能的原因

https://github.com/chatpire/chatgpt-web-share/issues/360#issuecomment-1923267842

大佬能看看吗？

**Comment by xqdoo00o** [comment]
是这个原因，不过我的账号还没灰度到这个功能，所以没法适配

**Comment by bi1101** [comment]
Hi, if this helps, I have attached a burner account in the file for you to have a look at. I have tested them and it has the error. Feel free to use them as you may like as this is only dummy account.
[accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14151264/accounts.txt)

**Comment by zeushera140** [comment]
3.5是好的，但是gpt-4不能回答了。

**Comment by bi1101** [comment]
嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户
[accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)

**Comment by zeushera140** [comment]
> 嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户 [accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)

https://github.com/maxduke/go-chatgpt-api  找到了一个可用的……就是没本仓库方便。

**Comment by bi1101** [comment]
> > 嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户 [accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)
> 
> https://github.com/maxduke/go-chatgpt-api 找到了一个可用的……就是没本仓库方便。

这能用在 GPT-4 上吗？我快修好 Websocket 了，但是不能用在 GPT-4 上？

**Comment by zeushera140** [comment]
> > > 嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户 [accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)
> > 
> > 
> > https://github.com/maxduke/go-chatgpt-api 找到了一个可用的……就是没本仓库方便。
> 
> 这能用在 GPT-4 上吗？我快修好 Websocket 了，但是不能用在 GPT-4 上？@zeushera140

能用gpt-4，不过不是很稳定。

**Comment by bi1101** [comment]
> > > > > 嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户 [accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)
> > > > 
> > > > 
> > > > https://github.com/maxduke/go-chatgpt-api 找到了一个可用的……就是没本仓库方便。
> > > 
> > > 
> > > 这能用在 GPT-4 上吗？我快修好 Websocket 了，但是不能用在 GPT-4 上？@zeushera140
> > 
> > 能用gpt-4，不过不是很稳定。
> 
> 这个当初我改完就没WSS了，没怎么测过

Wss 只影响某些账户，我在上面附上了一个受影响的团队账户。我正在为当前的仓库修复 wss 问题，但有时候我仍然会因某些原因从 wss 那里得到空响应。这真的很奇怪。这可能是某种速率限制，但没有给出错误消息。在实现 wss 时，你有没有注意到任何空响应？

**Comment by zeushera140** [comment]
> > > > > > > 嗨，你可以重新审视这个问题吗？看起来GPT-4也不再工作了，即使对于未受影响的账户也是如此。这是一个受影响的团队账户 [accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/14313820/accounts.txt)
> > > > > > 
> > > > > > 
> > > > > > https://github.com/maxduke/go-chatgpt-api 找到了一个可用的……就是没本仓库方便。
> > > > > 
> > > > > 
> > > > > 这能用在 GPT-4 上吗？我快修好 Websocket 了，但是不能用在 GPT-4 上？@zeushera140
> > > > 
> > > > 
> > > > 能用gpt-4，不过不是很稳定。
> > > 
> > > 
> > > 这个当初我改完就没WSS了，没怎么测过
> > 
> > 
> > 感谢作者。能用……有其他好用的库么
> 
> 现在好像一般都在用ninja那个吧，那个自带的转API模式的听说不维护了，不知道是否可用。 还有个 https://github.com/xyhelper/chat2api ，不确定现在能否用

好的，多谢，我试试看

**Comment by zeushera140** [comment]
作者更新本库了……不过好像还是不行，至少我的gpt-3.5-turbo还是返回空……

**Comment by xqdoo00o** [comment]
May fixed, just try the newest commit
