### ISSUE TITLE
早上突然就不行了 Failed to get CSRF token

### ISSUE THREAD

**Issue by dreammis** [xqdoo00o/ChatGPT-to-API#32]
Location: begin
10:31:28 Status code: 0
Details: Failed to get CSRF token

好奇怪，更换代理，重新更新har文件，均不行

**Comment by zeushera140** [comment]
一直报错，code 500……换了chat2api也是。估计官方改东西了

**Comment by Jaspix** [comment]
我有同样的问题

**Comment by xqdoo00o** [comment]
请更新最新版

**Comment by zeushera140** [comment]
> 请更新最新版

ok了，感谢

**Comment by dreammis** [comment]
> 请更新最新版

可以了感谢
