### ISSUE TITLE
大佬 请问支持画图和阅读文档吗

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [xqdoo00o/ChatGPT-to-API#36]
gpts支持嘛

**Comment by yuanshangyujingshierlou** [comment]
如何赞助作者呢

**Comment by yuanshangyujingshierlou** [comment]
> 这只能用免费的chatgpt-3.5，不支持画图。 也不支持阅读文档。 这个项目只是把免费web 端 chatgpt-3.5 包装成一个chatgpt 兼容的api 地址，然后在其他需要chatgpt api key 的软件里面调用而已。

可以用gpt4啊 我试了

**Comment by yuanshangyujingshierlou** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/81788251/b8bacdaf-a255-4a34-bfe6-f556695dfd8e)

**Comment by xqdoo00o** [comment]
需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口

**Comment by yuanshangyujingshierlou** [comment]
> 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口

好的 谢谢大佬 是不支持backend接口吗

**Comment by xqdoo00o** [comment]
> > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> 
> 好的 谢谢大佬 是不支持backend接口吗

肯定支持呀，不支持怎么转api的。但是要兼容官方api的，才没有上传文件功能

**Comment by think007** [comment]
> > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> 
> 好的 谢谢大佬 是不支持backend接口吗

accouns.txt在根目录吗

**Comment by yuanshangyujingshierlou** [comment]
> > > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> > 
> > 
> > 好的 谢谢大佬 是不支持backend接口吗
> 
> accouns.txt在根目录吗

是的

**Comment by King-Of-Knights** [comment]
@xqdoo00o 大佬好呀，调用GPT-4画图，API地址似乎是`/v1/images/generations`，但是我看找个项目里面好像没有呀

**Comment by xqdoo00o** [comment]
> @xqdoo00o 大佬好呀，调用GPT-4画图，API地址似乎是`/v1/images/generations`，但是我看找个项目里面好像没有呀

目前实现的方式是调chat接口gpt-4模型，就像你在官网gpt-4画图那样

**Comment by xqdoo00o** [comment]
> > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> 
> 好的 谢谢大佬 是不支持backend接口吗

支持上传文件了，模拟的api接口格式参考https://platform.openai.com/docs/guides/vision
里面的url字段换成你要上传文件的url，或者[转data uri](https://www.adminbooster.com/tool/data_uri)。

**Comment by yuanshangyujingshierlou** [comment]
> > > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> 
> > 
> 
> > 好的 谢谢大佬 是不支持backend接口吗
> 
> 
> 
> 支持上传文件了，模拟的api接口格式参考https://platform.openai.com/docs/guides/vision
> 
> 里面的url字段换成你要上传文件的url，或者[转data uri](https://www.adminbooster.com/tool/data_uri)。
> 
> 需要账号有plus

大佬牛批，怎么赞助一下，赞助一周咖啡

**Comment by yuanshangyujingshierlou** [comment]
> > > 需要你的openai账号是plus，然后把账号密码放到accouns.txt中登录，就可以调gpt-4画图了，阅读文档不支持，因为官方api没有上传接口
> > 
> > 
> > 好的 谢谢大佬 是不支持backend接口吗
> 
> 支持上传文件了，模拟的api接口格式参考https://platform.openai.com/docs/guides/vision 里面的url字段换成你要上传文件的url，或者[转data uri](https://www.adminbooster.com/tool/data_uri)。 需要账号有plus

```success read auth arkose
success read chat arkose
success read chat arkose
success read chat arkose
success read chat arkose
success read auth arkose
success read chat arkose
success read chat arkose
success read chat arkose
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
[GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
[GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
[GIN-debug] GET    /v1/models                --> main.simulateModel (5 handlers)
2024/04/16 08:53:59 2510736 0.0.0.0:7777
[GIN] 2024/04/16 - 08:54:08 | 500 |  819.349085ms |   118.89.83.240 | POST     "/v1/chat/completions"
```
大佬今天早上突然就请求500，我重新抓了一下har放进去，请求还是500，在官网上问问题也同样不通，会出现!
Something went wrong. If this issue persists please contact us through our help center at help.openai.com.这种报错，换了个节点又可以在官网使用了，是vps的ip被拉黑了吗，还是因为啥特征问题呢

**Comment by xqdoo00o** [comment]
@yuanshangyujingshierlou 更新下最新版

**Comment by yuanshangyujingshierlou** [comment]
> @yuanshangyujingshierlou 更新下最新版

大佬牛批，这么快就解决了

**Comment by yuanshangyujingshierlou** [comment]
> @yuanshangyujingshierlou 更新下最新版

```success read auth arkose
success read chat arkose
success read chat arkose
success read chat arkose
success read chat arkose
success read auth arkose
success read chat arkose
success read chat arkose
success read chat arkose
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
[GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
[GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
[GIN-debug] GET    /v1/models                --> main.simulateModel (5 handlers)
2024/04/16 09:39:39 2516752 0.0.0.0:7777

[GIN] 2024/04/16 - 09:40:09 | 200 |      56.511µs |   118.89.83.240 | GET      "/ping"
2024/04/16 09:40:13 [STOP - Hammer Time] Forcefully shutting down parent
2024/04/16 09:40:13 2516649 Serve() returning...
```
大佬 好像又G了

**Comment by yuanshangyujingshierlou** [comment]
很奇怪 过了一会儿又好了，之前一直是504超时，然后一段时间又可以正常请求了，但是请求的延时都在30秒左右
```[GIN] 2024/04/16 - 09:48:00 | 200 | 28.160883789s |   118.89.83.240 | POST     "/v1/chat/completions"
[GIN] 2024/04/16 - 09:48:04 | 200 | 19.972372813s |   118.89.83.240 | POST     "/v1/chat/completions"
[GIN] 2024/04/16 - 09:48:14 | 200 | 29.793985765s |   118.89.83.240 | POST     "/v1/chat/completions"
[GIN] 2024/04/16 - 09:48:17 | 200 | 12.406708292s |   118.89.83.240 | POST     "/v1/chat/completions"
[GIN] 2024/04/16 - 09:48:17 | 200 | 32.763658395s |   118.89.83.240 | POST     "/v1/chat/completions"
```
