### ISSUE TITLE
本地运行报错unable to check chat requirement

### ISSUE THREAD

**Issue by think007** [xqdoo00o/ChatGPT-to-API#37]
{
"error": "unable to check chat requirement"
}
开了梯子，https://chat.openai.com也能免登对话

**Comment by a857112551** [comment]
> { "error": "unable to check chat requirement" } 开了梯子，[https://chat.openai.com也能免登对话](https://chat.openai.com%E4%B9%9F%E8%83%BD%E5%85%8D%E7%99%BB%E5%AF%B9%E8%AF%9D)

请问怎么解决的啊，我现在是拉取代码编译部署到vps上了，在ChatGPT-Next-Web页面中设置好了也是报这个错

**Comment by xqdoo00o** [comment]
首先检测代理ip使用浏览器打开官网是否正常使用，检测是否代理了域名chatgpt.com。如果都没问题的话，请添加下环境变量export CLIENT_PROFILE=[这里的键值](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA
