### ISSUE TITLE
运行报错Error getting auth Arkose token

### ISSUE THREAD

**Issue by think007** [xqdoo00o/ChatGPT-to-API#38]
success read chat arkose
Updating access token for 邮箱@outlook.com
Error getting auth Arkose token
Location: begin
Status code: 0
Details: a valid HAR file which contains login arkose is required
HAR文件也放入了程序同级的`harPool`文件夹里
`accounts.txt` - 也存放OpenAI账号邮箱和密码

**Comment by xqdoo00o** [comment]
你这个报错意思是缺少登录har
参考[doc](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)

使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选**保留日志**选项。
登录https://chat.openai.com/

**Comment by think007** [comment]
> 你这个报错意思是缺少登录har 参考[doc](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)
> 
> 使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选**保留日志**选项。 登录https://chat.openai.com/

那如果有多个账号也需要放多个har文件，har文件名称可以随意没

**Comment by think007** [comment]
> 你这个报错意思是缺少登录har 参考[doc](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)
> 
> 使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选**保留日志**选项。 登录https://chat.openai.com/

还是报错，HAR文件也放入了程序同级的harPool文件夹里
accounts.txt - 也存放OpenAI账号邮箱和密码
success read chat arkose
Updating access token for 邮箱账号@outlook.com
Error getting auth Arkose token
Location: begin
Status code: 0
Details: a valid HAR file which contains login arkose is required

**Comment by xqdoo00o** [comment]
> > 你这个报错意思是缺少登录har 参考[doc](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)
> > 使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选**保留日志**选项。 登录https://chat.openai.com/
> 
> 还是报错，HAR文件也放入了程序同级的harPool文件夹里 accounts.txt - 也存放OpenAI账号邮箱和密码 success read chat arkose Updating access token for 邮箱账号@outlook.com Error getting auth Arkose token Location: begin Status code: 0 Details: a valid HAR file which contains login arkose is required

你打开har文件，搜一下里面有没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C
没有的话，建议重新操作下，**勾选保留日志选项后，再登录https://chat.openai.com/  !!!!**

**Comment by xqdoo00o** [comment]
> accounts.txt - 也存放OpenAI账号邮箱和密码
> success read chat arkose
> Updating access token for 邮箱账号@outlook.com
> Error getting auth Arkose token

如果有登录har，这里会多打印一个success read login arkose，**建议仔细阅读上文操作步骤 !!!!**

**Comment by think007** [comment]
> 0A1D34FC-659D-4E23-B17B-694DCFCF6A6C



> > > 你这个报错意思是缺少登录har 参考[doc](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)
> > > 使用基于chromium的浏览器（Chrome，Edge）打开浏览器开发者工具（F12），并切换到网络标签页，勾选**保留日志**选项。 登录https://chat.openai.com/
> > 
> > 
> > 还是报错，HAR文件也放入了程序同级的harPool文件夹里 accounts.txt - 也存放OpenAI账号邮箱和密码 success read chat arkose Updating access token for 邮箱账号@outlook.com Error getting auth Arkose token Location: begin Status code: 0 Details: a valid HAR file which contains login arkose is required
> 
> 你打开har文件，搜一下里面有没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C 没有的话，建议重新操作下，**勾选保留日志选项后，再登录https://chat.openai.com/ !!!!**

没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C是不是ios的plus没有这个

**Comment by bi1101** [comment]
> 没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C是不是ios的plus没有这个

Hi, have you log out and login again while turning on `preserve log`? It should get detected that way, the har for auth only get saved if you log out and log in again

**Comment by think007** [comment]
> If Har is not an option, just use cookies.json manually. It should work even if HAR doesn't

 cookies.json 来个参考格式

**Comment by xqdoo00o** [comment]
> > If Har is not an option, just use cookies.json manually. It should work even if HAR doesn't
> 
> cookies.json 来个参考格式

你是第三方账号？不是输入邮箱密码登录的那种账号？

**Comment by think007** [comment]
> 没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C是不是ios的plus没有这个

现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录

**Comment by think007** [comment]
> > > If Har is not an option, just use cookies.json manually. It should work even if HAR doesn't
> > 
> > 
> > cookies.json 来个参考格式
> 
> 你是第三方账号？不是输入邮箱和密码登录的那种账号？

现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录

**Comment by xqdoo00o** [comment]
> 现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录

https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE
参考这里添加cookies.json文件，账户名就是你的账号邮箱

**Comment by think007** [comment]
> > 现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录
> 
> https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE 参考这里添加cookies.json文件，账户名就是你的账号邮箱

{
    "第三方账户名": [
        {
            "Name": "__Secure-next-auth.session-token",
            "Value": "网页登录第三方账户后，cookies中的__Secure-next-auth.session-token值",
            "Path": "/",
            "Domain": "",
            "Expires": "0001-01-01T00:00:00Z",
            "MaxAge": 0,
            "Secure": true,
            "HttpOnly": true,
            "SameSite": 2,
            "Unparsed": null
        }
    ]
}这一段是加在accounts.txt还是cookies.json，加在accounts.txt会提示超出长度之类提示错误

**Comment by xqdoo00o** [comment]
> > > 现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录
> > 
> > 
> > https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE 参考这里添加cookies.json文件，账户名就是你的账号邮箱
> 
> { "第三方账户名": [ { "Name": "__Secure-next-auth.session-token", "Value": "网页登录第三方账户后，cookies中的__Secure-next-auth.session-token值", "Path": "/", "Domain": "", "Expires": "0001-01-01T00:00:00Z", "MaxAge": 0, "Secure": true, "HttpOnly": true, "SameSite": 2, "Unparsed": null } ] }这一段是加在accounts.txt还是cookies.json，加在accounts.txt会提示超出长度之类提示错误

新建的cookies.json文件

**Comment by think007** [comment]
> accounts.txt



> > > > 现在问题是har文件没有0A1D34FC-659D-4E23-B17B-694DCFCF6A6C不知道是不是ios的plus没有这个，有没有其他解决方法。不是第三方账号登录
> > > 
> > > 
> > > https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE 参考这里添加cookies.json文件，账户名就是你的账号邮箱
> > 
> > 
> > { "第三方账户名": [ { "Name": "__Secure-next-auth.session-token", "Value": "网页登录第三方账户后，cookies中的__Secure-next-auth.session-token值", "Path": "/", "Domain": "", "Expires": "0001-01-01T00:00:00Z", "MaxAge": 0, "Secure": true, "HttpOnly": true, "SameSite": 2, "Unparsed": null } ] }这一段是加在accounts.txt还是cookies.json，加在accounts.txt会提示超出长度之类提示错误
> 
> 新建的cookies.json文件

accounts.txt里面添加账户和密码，新建的cookies.json文件放参数运行起来回复的3.5不是4.0：{
        "第三方账户名": [
            {
                "Name": "__Secure-next-auth.session-token",
                "Value": "网页登录第三方账户后，cookies中的__Secure-next-auth.session-token值",
                "Path": "/",
                "Domain": "",
                "Expires": "0001-01-01T00:00:00Z",
                "MaxAge": 0,
                "Secure": true,
                "HttpOnly": true,
                "SameSite": 2,
                "Unparsed": null
            }
        ]
    }

**Comment by xqdoo00o** [comment]
@think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗

**Comment by think007** [comment]
> @think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗

是的

**Comment by xqdoo00o** [comment]
> > @think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗
> 
> 是的

运行后，会自动创建一个access_tokens.json的文件吗？有的话，里面有内容吗？里面puid这个字段有内容吗？

**Comment by think007** [comment]
> > > @think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗
> > 
> > 
> > 是的
> 
> 运行后，会自动创建一个access_tokens.json文件吗？有的话，里面有内容吗？里面puid这个字段有内容吗？

access_tokens没有内容

**Comment by xqdoo00o** [comment]
> > > > @think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗
> > > 
> > > 
> > > 是的
> > 
> > 
> > 运行后，会自动创建一个access_tokens.json文件吗？有的话，里面有内容吗？里面puid这个字段有内容吗？
> 
> access_tokens没有内容

那就是没登陆上，把敏感信息脱敏后 accounts.txt和cookies.json发一下

**Comment by think007** [comment]
> > > > > @think007 accounts.txt里的账户名，和cookies.json里的账户名是同一个吗
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 运行后，会自动创建一个access_tokens.json文件吗？有的话，里面有内容吗？里面puid这个字段有内容吗？
> > 
> > 
> > access_tokens没有内容
> 
> 那就是没登陆上，把敏感信息脱敏后 accounts.txt和cookies.json发一下

有TG没

**Comment by xqdoo00o** [comment]
> 有TG没

@pikachu668
