### ISSUE TITLE
继续对话的时候会在没有完成对话的时候就返回

### ISSUE THREAD

**Issue by zhenyuefu** [xqdoo00o/ChatGPT-to-API#4]
Continuing conversation
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 403

继续对话的会在没有完成对话时就返回错误“Our systems have detected unusual activity from your system. Please try again later.” 但是状态码却是200

后面的请求出现Only one message at a time.错误。

**Comment by xqdoo00o** [comment]
是不是ENABLE_HISTORY设置为了false，这样的话无法继续会话

**Comment by zhenyuefu** [comment]
ENABLE_HISTORY设置为true依旧有这个问题，使用的是gpt4

**Comment by xqdoo00o** [comment]
> ENABLE_HISTORY设置为true依旧有这个问题，使用的是gpt4

请拉取最新版编译后，再试试

**Comment by zhenyuefu** [comment]
下午开始直接获取arkose token失败了 提示captcha required

**Comment by xqdoo00o** [comment]
> 下午开始直接获取arkose token失败了 提示captcha required

已修复，可以再试试

**Comment by bi1101** [comment]
> 是不是ENABLE_HISTORY设置为了false，这样的话无法继续会话，因为不存在该历史记录

I'm curious, Is there any way to set Enable history as "false" but still be able to continue long messages?

It's because if Enable history is "true" on the Chat GPT web app, there are a lot of annoying "New Chat" conversation

**Comment by xqdoo00o** [comment]
My mistake, the 403 error is because of use old arkose token, none of the history business. Removed the unused fixed now.
Build with the latest version, you could set Enable history as "false" and still be able to continue long messages.
