### ISSUE TITLE
现在是不是识别方式改了，开始疯狂封号了？

### ISSUE THREAD

**Issue by zeushera140** [xqdoo00o/ChatGPT-to-API#41]
我前几天刚被封了1个plus账号，现在第二个也被封了，换VPN ip也没用……不敢用了
只要用gpt-4超过一定时间，好像就会被封

**Comment by xqdoo00o** [comment]
应该是你账号付款方式的原因，我一直再用，没被封过。
你如果担心被封，可以先用着官网

**Comment by zeushera140** [comment]
> 应该是你账号付款方式的原因，我一直再用，没被封过。 你如果担心被封，可以先用着官网

用的iOS礼品卡……谢谢回复，我想想办法
