### ISSUE TITLE
"error": "No websocket connection"

### ISSUE THREAD

**Issue by lc82111** [xqdoo00o/ChatGPT-to-API#46]
./freechatgpt
success read auth arkose
success read chat arkose
success read chat arkose
success read chat arkose
Updating access token for xxx@gmail.com
Success!
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
[GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
[GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
[GIN-debug] GET    /v1/models                --> main.simulateModel (5 handlers)
2024/04/27 18:05:55 1185704 127.0.0.1:8888
[GIN] 2024/04/27 - 18:06:13 | 500 | 12.068618495s |       127.0.0.1 | POST     "/v1/chat/completions"

之前都好好的。昨天plus过期又续费后，一直出现"error": "No websocket connection"，中间短暂可用2个小时后，又出现这个error。

已多次更新har文件，har文件严格按照先登录再对话的指示保存，并删除access_tokens.json，cookies.json。 

如果不设置accounts.txt，可以正常gpt3.5 api。一旦设置accounts.txt，就 no websocket connection.

chatGPT-to-API已更新最新版本。

我的chatGPT-to-API是Linux，chatGPT是Windows或mac，是不是需要我在windows或mac上装个chatGPT-to-API ?

请老大指个路，非常感谢。

**Comment by xqdoo00o** [comment]
请先查看官网是否可以正常使用

**Comment by lc82111** [comment]
> 请先查看官网是否可以正常使用
官网可以用的
我如果不设置accounts.txt，可以正常gpt3.5 api。一旦设置accounts.txt，就 no websocket connection.

**Comment by xqdoo00o** [comment]
几个号还没灰度到新的wss特性，所以暂时还没法改

**Comment by lc82111** [comment]
要不你用我的号
TG: @fanhaosu

**Comment by lc82111** [comment]
with the last commit, it seems all works as expected. close the issue.

**Comment by bi1101** [comment]
Hi, I believe the issue is happening again

**Comment by xqdoo00o** [comment]
> Hi, I believe the issue is happening again. The issue seems to happen only to certain accounts

Could you send me the account which happening?

**Comment by bi1101** [comment]
[accounts.txt](https://github.com/xqdoo00o/ChatGPT-to-API/files/15184030/accounts.txt)
Yes, these accounts are affected, (some personal workspace still work)

**Comment by xqdoo00o** [comment]
> Hi, I believe the issue is happening again. The issue seems to happen only to certain accounts

Done. Use the newer commit.
