### ISSUE TITLE
今天好像更新了，目前无法正常使用

### ISSUE THREAD

**Issue by Plus-xu** [xqdoo00o/ChatGPT-to-API#48]
https://chat.openai.com 现在会强制跳转到 https://chatgpt.com
用api会显示错误：
`API Error: Status Code 403, {"error":{"code":"error","message":"Unusual activity has been detected from your device. Try again later. (123-aaa)","param":null,"type":"403 Forbidden"}}`
官网可以正常使用

**Comment by zeushera140** [comment]
+1，换ip也没用。

**Comment by xqdoo00o** [comment]
好了
