### ISSUE TITLE
使用 go 1.22.3编译，运行报错

### ISSUE THREAD

**Issue by kylinpoet** [xqdoo00o/ChatGPT-to-API#50]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/6766883/f0b76de7-44d7-40e8-bbfa-7e93335781d6)

**Comment by xqdoo00o** [comment]
未复现，是否是最新的代码？

**Comment by kylinpoet** [comment]
是最新pull的代码，har文件是必需的吗？现在chatgpt.com域名获取不到原来的har了

**Comment by xqdoo00o** [comment]
确定是最新commit嘛，发下getconfig函数那里的截图

**Comment by kylinpoet** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/6766883/65f06e9c-9bf2-4d01-ad1f-269aa14bc9d0)

**Comment by xqdoo00o** [comment]
chatgpt.com是否没走代理，建议设置下规则走代理，新域名改为chatgpt.com了

**Comment by xqdoo00o** [comment]
使用最新commit，并设置chatgpt.com走代理
