### ISSUE TITLE
新代码404错误

### ISSUE THREAD

**Issue by RICHQAQ** [xqdoo00o/ChatGPT-to-API#53]
[GIN] 2024/05/14 - 21:42:24 | 404 |  937.436989ms |   154.12.xxx | POST     "/v1/chat/completions"
[GIN] 2024/05/14 - 21:42:25 | 404 |  516.464169ms |   154.12.xxx | POST     "/v1/chat/completions"
[GIN] 2024/05/14 - 21:42:26 | 404 |  671.040845ms |   154.12.xxx | POST     "/v1/chat/completions"
[GIN] 2024/05/14 - 21:42:54 | 404 |  1.620388804s |   154.12.xxx | POST     "/v1/chat/completions"
[GIN] 2024/05/14 - 21:42:55 | 404 |  579.647476ms |   154.12.xxx | POST     "/v1/chat/completions"
[GIN] 2024/05/14 - 21:43:00 | 404 |  392.099484ms |   154.12.xxx | POST     "/v1/chat/completions"
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/121705462/7f77b919-c9c3-4525-80b8-310df2da7001)

谢谢了

**Comment by RICHQAQ** [comment]
gpt-3.5-turbo和gpts是可以正常请求的，gpt-4和gpt-4o出的问题

**Comment by xqdoo00o** [comment]
gpt4传的模型名是什么

**Comment by gkingt** [comment]
普号也支持gpt-4o，看代码好像没有支持普号

**Comment by xqdoo00o** [comment]
已修复，打游戏太入迷 忘记测了😒
