### ISSUE TITLE
请求支持 refresh_token to access_token

### ISSUE THREAD

**Issue by baby9** [xqdoo00o/ChatGPT-to-API#54]
通过refresh_token 生成 access_token

通过官网获取 [https://auth0.openai.com/oauth/token](https://auth0.openai.com/oauth/token)  以下是python实现
```
import requests,json
url = "https://auth0.openai.com/oauth/token"
headers = {"Content-Type": "application/json"}
data = {
    "redirect_uri": "com.openai.chat://auth0.openai.com/ios/com.openai.chat/callback",
    "grant_type": "refresh_token",
    "client_id": "pdlLIX2Y72MIl2rhLhTE9VV9bN905kBh",
    "refresh_token": "替换成你的refresh_token"
}
response = requests.post(url, headers=headers, data=json.dumps(data))
print(response.json()["access_token"])
```

调用 [zhele](https://linux.do/t/topic/40591) 的免费api接口获取
```
import requests
url = "https://token.oaifree.com/api/auth/refresh"
headers = {
    "Content-Type": " x-www-form-urlencoded;charset=UTF-8"
}
data = {
    "refresh_token": "替换成你的refresh_token"
}
response = requests.post(url, data=data)
print(response.json()["access_token"])
```

**Comment by baby9** [comment]
refresh token 的有效期为永久, 且每次用 refresh token 刷新 access token 时得到的 access token 有效期都为10天

**Comment by xqdoo00o** [comment]
这个client_id是固定的嘛

**Comment by gkingt** [comment]
> 这个client_id是固定的嘛

是固定的

**Comment by baby9** [comment]
可以参考这两个项目
[https://github.com/qy527145/openai_token](https://github.com/qy527145/openai_token)
[https://zhile.io/2023/05/19/how-to-get-chatgpt-access-token-via-pkce.html](https://zhile.io/2023/05/19/how-to-get-chatgpt-access-token-via-pkce.html)

**Comment by xqdoo00o** [comment]
抄好了，参考[链接](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE)
首先accounts.txt里加上账户名和随意一个密码，然后cookies.json里如上链接所示，注意需把`Name`的值改为`refresh_token`
如果要测试是否正常获取的话，可以在[代码](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/auth.go#L234)前一行加上`fmt.Println(err)`

**Comment by xqdoo00o** [comment]
> 粗略测了下没问题，看了下代码应该目前只支持持单账号，对我来说没问题。 还有一点就是，用refresh_token的话，刷新时间没有必要每天一刷。看了下改动，因为在依赖上，主体程序上应该不太能判断。建议加个环境变量。可以自行控制每隔几天刷新。

PUID是7天有效期，和10天的公约数只有1了

**Comment by xqdoo00o** [comment]
> 我魔改的gochatgptapi 是7天一刷。可行么？

一天一刷也没啥问题，懒得改了，而且支持多账号呀，cookies.json里设置多个账户名和refresh_token就好了
