### ISSUE TITLE
unable to create ws tunnel

### ISSUE THREAD

**Issue by SMLYSR** [xqdoo00o/ChatGPT-to-API#57]
求助：
在mac本地编译运行和在vps ubuntu环境运行，启动访问都会返回：
{"error":"unable to create ws tunnel"}

在本地Golang中debug后发现调用接口403
![WX20240520-114417@2x](https://github.com/xqdoo00o/ChatGPT-to-API/assets/25998795/7ae2ad3e-1a29-4cd8-8213-e212a2c3096d)

vps上运行:
![WX20240520-114650@2x](https://github.com/xqdoo00o/ChatGPT-to-API/assets/25998795/bd0a97de-bdf4-438b-b315-2ce32af41b9e)

**Comment by xqdoo00o** [comment]
是否已登录账号? 换个代理ip试试，这个接口返回跟ip有关的。参考之前403的issue

**Comment by SMLYSR** [comment]
尝试使用免登录直接使用返回：unable to check chat requirement
