### ISSUE TITLE
Adding POW related env var

### ISSUE THREAD

**Issue by maxduke** [xqdoo00o/ChatGPT-to-API#60]
POW的问题好像还是没得到解决。

我自己加了几个环境变量
 - POW_RETRY_TIMES - POW难度太高时，尝试重新获取POW种子的次数，默认0
 - POW_MAX_DIFFICULTY - POW最高难度设定，高于此难度将重试获取POW种子，默认"000032"
 - POW_MAX_CALC_TIMES - 整数型，默认500000次。 CPU运算快的可以适当提高，减少403错误的概率

有需要的话我可以提个PR，或者直接抄改我代码 https://github.com/maxduke/ChatGPT-to-API 。
觉得不合适不需要的话，可以关了这个issue。 多谢。

**Comment by xqdoo00o** [comment]
> > 这些都是治标，不要用那个修复的commit加的另外一个环境变量的默认值就行了。
> > 对，没从根本上解决问题。
> > 话说换profile指纹，那个我这边试了没效果，还是好多00032。不知为什么......

首先确定用浏览器不是000032，除了profile的另一个环境变量，不用他的默认值

**Comment by nekomiya-hinata** [comment]
> 首先确定用浏览器不是000032，除了profile的另一个环境变量，不用他的默认值
官网上的32也挺多的，现在唯一的因素可能就是ip质量了
