### ISSUE TITLE
部分账号出现空回复

### ISSUE THREAD

**Issue by gkingt** [xqdoo00o/ChatGPT-to-API#61]
应该也不算空回复？好像是wss导致的

**Comment by xqdoo00o** [comment]
wss应该不会使用了，你用那些账号，postconversation函数里打印下`println(response.Header.Get("Content-Type"))`，结果应该有text/event-stream

**Comment by gkingt** [comment]
晚上回去我试一下

**Comment by gkingt** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/137085967/8932ca83-22e8-4ef4-9fba-36389253056d)
这是日志 有的200状态的Content-Type是application/json

**Comment by gkingt** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/137085967/7d4ff490-06d5-402f-b887-aa55f27adcde)

这是日志 有的200状态的请求的Content-Type是application/json

**Comment by xqdoo00o** [comment]
是最新版么，这些账号用浏览器官网是wss么

**Comment by gkingt** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/137085967/f7cd86be-4861-4ce3-a7d4-70ac5748b894)
在官网的

**Comment by xqdoo00o** [comment]
conversavtion接口的

**Comment by gkingt** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/137085967/8a770a5c-f984-4f7f-a7c2-a3cbf778fc2e)

**Comment by xqdoo00o** [comment]
看来是force_use_sse没生效，方便的话可以把有问题账号密码发我gmail邮箱里 用户名+gmail

**Comment by gkingt** [comment]
发了

**Comment by xqdoo00o** [comment]
没问题呀，没有空回复

**Comment by xqdoo00o** [comment]
500应该是跳force_login: true了，估计是你的ip质量不好，或者环境变量改下profile和ua试试

**Comment by gkingt** [comment]
好像确实是ip问题，换了个ip好了，谢谢佬
