### ISSUE TITLE
多账号使用gpt4o

### ISSUE THREAD

**Issue by WaveBird** [xqdoo00o/ChatGPT-to-API#62]
现在的项目支持多账号使用gpt4o吗? 如果某个账户额度用完了，自动切换新的账户？求支持？

**Comment by xqdoo00o** [comment]
会自动轮询（[文档](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E8%AE%BE%E7%BD%AE)）。
accounts.txt 例子 (a@a.com 是普通账户, b@b.com是teams账户，c@c.com是plus账户)
```
a@a.com:password:3
b@b.com:password:2/5
c@c.com:password
```
password后的是使用次数，默认值是1次。上例中
头3次请求使用账户a.
接下来5次使用账户b的teams workspace
接下来2次使用账户b的个人账户
接下来1次使用账户c
以此不断轮询
