### ISSUE TITLE
harpool下可以放多个har文件吗

### ISSUE THREAD

**Issue by gaoasi** [xqdoo00o/ChatGPT-to-API#68]
harpool下可以放多个用户下的har文件吗

**Comment by xqdoo00o** [comment]
可以，要不怎么叫pool呢

**Comment by gaoasi** [comment]
![image](https://github.com/xqdoo00o/ChatGPT-to-API/assets/43560964/7707eaf8-1409-40ad-a644-6b19c9b310d1)
这种情况是没有登陆成功吗

**Comment by xqdoo00o** [comment]
是最新版本嘛

**Comment by gaoasi** [comment]
是最新版本的，但我上午调试的时候没问题，下午重新放了har文件，就不行了

**Comment by xqdoo00o** [comment]
请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA

**Comment by gaoasi** [comment]
> 更新最新版，请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA

这个加了，现在好像是账号登不上去的问题

**Comment by xqdoo00o** [comment]
> > 更新最新版，请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA
> 
> 这个加了，现在好像是账号登不上去的问题

更新下午刚发的新版后，再试试能不能登录

**Comment by gaoasi** [comment]
> > > 更新最新版，请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA
> > 
> > 
> > 这个加了，现在好像是账号登不上去的问题
> 
> 更新下午刚发的新版后，再试试能不能登录
可以了，感谢大佬解惑
