### ISSUE TITLE
turnstile chat-requirements

### ISSUE THREAD

**Issue by maxduke** [xqdoo00o/ChatGPT-to-API#69]
好像现在很多号chat-requirements都出turnstile了，看起来现在后端还没开始验证，就怕偷偷摸摸后端验证不过就降智
大佬有空可以看下
https://linux.do/t/topic/114850

**Comment by danepoirier0** [comment]
试了几个号，都有这个值了

**Comment by xqdoo00o** [comment]
动态类型处理过于复杂，还是研究下go里怎么调js代码吧

**Comment by xqdoo00o** [comment]
可以了，不过官网还没验证就先不开，后面开验证了可以自行删除[此行代码](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/internal/chatgpt/turnstile.go#L373)，就可以打开了

**Comment by danepoirier0** [comment]
大佬牛逼，Chatgpt的那段js代码太让人头疼

**Comment by 0xShawnLai** [comment]
好像更新了，取消掉注释，报错
interface conversion: interface {} is nil, not chatgpt.FuncType

e := token[0].(float64)
好像有一些e没映射上

**Comment by GPW9795** [comment]
直接跑不太能跑通，跟楼上报的错一样
