### ISSUE TITLE
The new update from Open AI seems to f*** up the Access Token & PUID Auth

### ISSUE THREAD

**Issue by bi1101** [xqdoo00o/ChatGPT-to-API#7]
Since yesterday, the Auth has been returning stuff like this, I tried proxy, no proxy, using my local machine, but nothing works. The HAR has also been provided

Updating access token for *****@*****.com
Error getting auth Arkose token
Location: begin
Status code: 0
Details: a valid HAR file required

**Comment by bi1101** [comment]
似乎HAR文件是问题所在，我可以看到
```
success read chat arkose
``` 
但仍然存在错误
```
a valid HAR file required
``` 
也许结构已经改变了？

我是唯一一个遇到这个错误的吗？

**Comment by bi1101** [comment]
似乎旧版本的存储库没有这个问题。

**Comment by xqdoo00o** [comment]
账号新登录也需要arkose了，你需要浏览器控制台保存日志 重新登录账号后，保存下har文件
