### ISSUE TITLE
最新Docker编译版本无法正常使用，无法识别HAR

### ISSUE THREAD

**Issue by Plus-xu** [xqdoo00o/ChatGPT-to-API#73]
操作系统：Debian 5.10.197 x86_64
安装方式：[Dockerfile](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/Dockerfile) 编译
账号登录方式：Google账号登录ChatGPT, Plus版本
上次可以正常运行的版本：好像是6月1日的版本

1. Dockerfile中golang版本已无法正常编译，修改为golang:1.22-alpine后可以正常编译
2. Docker编译的版本无法正常识别HAR（按照以前可以正常使用的方法获取）

```
chatgpttoapi  | Error: not a HAR file! 
chatgpttoapi  | Updating access token for xxx@gmail.com 
chatgpttoapi  | Success! 
chatgpttoapi  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
```

`chatgpttoapi  | Error getting Arkose token:  a valid HAR file which contains gpt-4 arkose is required
`

**Comment by xqdoo00o** [comment]
确实新版本要1.22了，
这个har是什么浏览器导出的，能用文本编辑器打开 并找到 fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147字符串吗

**Comment by xqdoo00o** [comment]
能发一下har文件吗，未复现。

**Comment by Plus-xu** [comment]
> 能发一下har文件吗，未复现。

好的，直接发在这里吗？或者发邮件？

**Comment by xqdoo00o** [comment]
邮件吧

**Comment by xqdoo00o** [comment]
xqdoo00o@gmail.com

**Comment by Plus-xu** [comment]
> [xqdoo00o@gmail.com](mailto:xqdoo00o@gmail.com)

已发送，谢谢

**Comment by xqdoo00o** [comment]
![image](https://github.com/user-attachments/assets/c03428f9-bbfe-4fac-8b08-608eab8e9fc1)
这里json错误

**Comment by Plus-xu** [comment]
> ![image](https://private-user-images.githubusercontent.com/12299238/348809145-c03428f9-bbfe-4fac-8b08-608eab8e9fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjcwMTksIm5iZiI6MTcyMTA2NjcxOSwicGF0aCI6Ii8xMjI5OTIzOC8zNDg4MDkxNDUtYzAzNDI4ZjktYmJmZS00ZmFjLThiMDgtNjA4ZWFiOGU5ZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE4MDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODFlMDk3OWJjNmQ1Y2YwMjEyYTYxOWJhYTU2ZDNjMjkyNjYxODY2ZjYzOGU0NTc0Zjg4MGFhNzMzODY1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPvUhk_sIThVMHnj95oGf_76ywvhvZbi7AF_o_WyOTs) 这里json错误

我又重新获取了2次HAR，发现每次获取的文件中都存在几处不同位置和类型的格式错误，几个月以前获取的HAR不存在格式问题，看不懂什么情况了...
![image](https://github.com/user-attachments/assets/04d7a8f1-1dfd-4092-b664-b5d93630f12e)
这些错误有关系吗？

**Comment by xqdoo00o** [comment]
如果没手动修改过，那就是chrome的bug，等chrome修复好了
