### ISSUE TITLE
获取token报错

### ISSUE THREAD

**Issue by gkingt** [xqdoo00o/ChatGPT-to-API#8]
现在获取token会出错，大佬有空修复一下

**Comment by bi1101** [comment]
这可能需要一些时间，因为登录界面添加了Arkose令牌

**Comment by xqdoo00o** [comment]
账号新登录需要arkose了，你需要浏览器控制台保存日志 重新登录账号后，保存下har文件
或者干脆手动把next-auth.session-token存到cookies.json里 参考[cookies.json](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE)，这里第一方账号也可以的

**Comment by bi1101** [comment]
"cookies.json" 方法对我有效！非常感谢！

**Comment by gkingt** [comment]
同样有效，非常感谢

**Comment by gkingt** [comment]
> 账号新登录需要arkose了，你需要浏览器控制台 勾选保留日志 并重新登录账号后，保存下har文件
> 
> 或者干脆手动把next-auth.session-token存到cookies.json里，放弃使用程序登录好了，参考[cookies.json](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE)，这里第一方账号也可以的

我看到4.0实现了联网功能，3.5可以实现吗

**Comment by bi1101** [comment]
> > 账号新登录需要arkose了，你需要浏览器控制台 勾选保留日志 并重新登录账号后，保存下har文件
> > 
> > 或者干脆手动把next-auth.session-token存到cookies.json里，放弃使用程序登录好了，参考[cookies.json](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#%E5%8F%AF%E9%80%89%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE)，这里第一方账号也可以的
> 
> 我看到4.0实现了联网功能，3.5可以实现吗

那个功能只在GPT-4的Plus订阅中可用。

**Comment by gkingt** [comment]
可惜
